#!/usr/bin/env python3
"""Create plots and a physics report for generated atmospheric-neutrino truth."""

# Import command-line parsing so callers can override the default files.
import argparse
# Import operating-system support for configuring Matplotlib's cache.
import os
# Import Path for platform-independent path handling.
from pathlib import Path
# Import text wrapping for readable PDF report pages.
import textwrap

# Resolve this script's directory so defaults do not depend on the current working directory.
SCRIPT_DIR = Path(__file__).resolve().parent
# Keep Matplotlib's cache in the analysis directory.
os.environ.setdefault("MPLCONFIGDIR", str(SCRIPT_DIR / ".matplotlib"))

# Import Awkward Array for ROOT's variable-length particle records.
import awkward as ak
# Import Matplotlib after configuring its cache location.
import matplotlib
# Select the batch backend because this script writes files rather than opening windows.
matplotlib.use("Agg")
# Import the plotting interface used for all figures.
import matplotlib.pyplot as plt
# Import PdfPages to create plot and report PDF collections.
from matplotlib.backends.backend_pdf import PdfPages
# Import NumPy for kinematic calculations, histogramming, and statistics.
import numpy as np
# Import uproot to read the Q-Pix Geant4 ROOT file without PyROOT.
import uproot

# Point the default input at the atmospheric-neutrino Geant4 production file.
DEFAULT_INPUT = SCRIPT_DIR.parent.parent / "02_qpix_geant4" / "output" / "atmospheric_g4.root"
# Store the plot collection beside the muon and kaon PDFs.
DEFAULT_PLOT_PDF = SCRIPT_DIR / "outputs" / "atmospheric_neutrino_truth_checks.pdf"
# Store the interpretation as a separate requested PDF.
DEFAULT_REPORT_PDF = SCRIPT_DIR / "outputs" / "atmospheric_neutrino_truth_report.pdf"
# Store individual figures in a particle-study-specific PNG folder.
DEFAULT_PNG_DIRECTORY = SCRIPT_DIR / "outputs" / "neutrino_pngs"
# Define the four atmospheric flavors generated by this workflow.
FLAVOR_PDGS = (12, -12, 14, -14)
# Provide conventional plot labels for each neutrino flavor.
FLAVOR_LABELS = {12: r"$\nu_e$", -12: r"$\bar\nu_e$", 14: r"$\nu_\mu$", -14: r"$\bar\nu_\mu$"}
# Provide plain-text names for prose and compact annotations.
FLAVOR_NAMES = {12: "nu_e", -12: "anti-nu_e", 14: "nu_mu", -14: "anti-nu_mu"}
# Assign stable, distinguishable colors to all four flavors.
FLAVOR_COLORS = {12: "#2166ac", -12: "#67a9cf", 14: "#b2182b", -14: "#ef8a62"}
# Map each incoming flavor to its expected charged lepton in a charged-current interaction.
EXPECTED_CHARGED_LEPTON = {12: 11, -12: -11, 14: 13, -14: -13}


# Parse command-line arguments.
def parse_args() -> argparse.Namespace:
    # Create a concise command-line description.
    parser = argparse.ArgumentParser(description="Analyze generated atmospheric-neutrino truth from event_tree.")
    # Accept a different Geant4 truth ROOT file.
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Geant4 ROOT file containing event_tree.")
    # Accept a different plot-collection PDF path.
    parser.add_argument("--plot-pdf", type=Path, default=DEFAULT_PLOT_PDF, help="PDF containing all neutrino plots.")
    # Accept a different report PDF path.
    parser.add_argument("--report-pdf", type=Path, default=DEFAULT_REPORT_PDF, help="PDF containing plot interpretation.")
    # Accept a different directory for standalone PNG figures.
    parser.add_argument("--png-directory", type=Path, default=DEFAULT_PNG_DIRECTORY, help="Directory for individual PNGs.")
    # Return the parsed options.
    return parser.parse_args()


# Save one figure into the plot PDF and as a high-resolution standalone PNG.
def save_plot(pdf: PdfPages, figure: plt.Figure, png_path: Path) -> None:
    # Resolve subplot spacing before writing either representation.
    figure.tight_layout()
    # Append the completed figure to the plot collection.
    pdf.savefig(figure)
    # Save the same figure as an individual PNG.
    figure.savefig(png_path, dpi=200)
    # Release figure memory.
    plt.close(figure)


# Add a compact statistics box to one plot panel.
def annotate(axis: plt.Axes, lines: list[str], location: tuple[float, float] = (0.98, 0.97)) -> None:
    # Draw all supplied lines in a translucent white box.
    axis.text(location[0], location[1], "\n".join(lines), transform=axis.transAxes, ha="right", va="top", fontsize=8.8,
              bbox={"facecolor": "white", "edgecolor": "0.7", "alpha": 0.90})


# Append one portrait report page using stable figure-relative coordinates.
def add_report_page(pdf: PdfPages, title: str, sections: list[tuple[str, str]], page_label: str) -> None:
    # Create a US-letter portrait page.
    figure = plt.figure(figsize=(8.5, 11.0))
    # Draw the report title with Matplotlib's dedicated page-title mechanism for stable PDF placement.
    figure.suptitle(title, x=0.08, y=0.94, fontsize=18, fontweight="bold", va="top", ha="left")
    # Start the first section below the title.
    y_position = 0.88
    # Draw each heading and wrapped paragraph in order.
    for heading, paragraph in sections:
        # Draw the section heading.
        figure.text(0.08, y_position, heading, fontsize=12, fontweight="bold", va="top", ha="left")
        # Move below the heading.
        y_position -= 0.035
        # Wrap prose at a width that matches the usable page area.
        wrapped = textwrap.fill(paragraph, width=92)
        # Draw the wrapped paragraph.
        figure.text(0.08, y_position, wrapped, fontsize=9.8, va="top", ha="left", linespacing=1.35)
        # Reserve vertical space based on the wrapped line count.
        y_position -= 0.027 * (wrapped.count("\n") + 1) + 0.035
    # Add a subtle page label.
    figure.text(0.86, 0.04, page_label, fontsize=8.5, color="0.4", ha="right")
    # Append the report page.
    pdf.savefig(figure)
    # Release figure memory.
    plt.close(figure)


# Extract one incoming neutrino and relevant final-state truth from every event.
def read_truth(input_path: Path) -> tuple[dict[str, ak.Array], int]:
    # List only branches required by this study.
    branches = [
        "generator_initial_particle_pdg_code",
        "generator_initial_particle_energy",
        "generator_initial_particle_px",
        "generator_initial_particle_py",
        "generator_initial_particle_pz",
        "generator_final_particle_pdg_code",
    ]
    # Open the ROOT file in a context manager.
    with uproot.open(input_path) as root_file:
        # Require the standard event tree.
        if "event_tree" not in root_file:
            # Raise a focused schema error.
            raise KeyError(f"No event_tree was found in {input_path}")
        # Access the latest event_tree cycle.
        tree = root_file["event_tree"]
        # Identify absent schema requirements.
        missing = sorted(set(branches).difference(tree.keys()))
        # Stop before loading if the file is incompatible.
        if missing:
            # Report all missing branches in one exception.
            raise KeyError("Missing required event_tree branches: " + ", ".join(missing))
        # Load the selected jagged arrays.
        arrays = tree.arrays(branches, library="ak", how=dict)
        # Record the number of interactions.
        event_count = int(tree.num_entries)
    # Return the loaded truth and event count.
    return arrays, event_count


# Run the complete atmospheric-neutrino truth study.
def main() -> None:
    # Read command-line arguments.
    args = parse_args()
    # Resolve the input path for validation and reporting.
    input_path = args.input.expanduser().resolve()
    # Resolve the plot PDF path.
    plot_pdf_path = args.plot_pdf.expanduser().resolve()
    # Resolve the report PDF path.
    report_pdf_path = args.report_pdf.expanduser().resolve()
    # Resolve the standalone PNG directory.
    png_directory = args.png_directory.expanduser().resolve()
    # Require an existing ROOT input.
    if not input_path.is_file():
        # Include the exact missing path in the error.
        raise FileNotFoundError(f"Geant4 ROOT file does not exist: {input_path}")
    # Create the plot PDF parent directory.
    plot_pdf_path.parent.mkdir(parents=True, exist_ok=True)
    # Create the report PDF parent directory.
    report_pdf_path.parent.mkdir(parents=True, exist_ok=True)
    # Create the standalone PNG directory.
    png_directory.mkdir(parents=True, exist_ok=True)
    # Read all required truth branches.
    arrays, event_count = read_truth(input_path)
    # Read initial-state particle identifiers, which include the target nucleus.
    initial_pdg = arrays["generator_initial_particle_pdg_code"]
    # Select only the four supported atmospheric neutrino flavors.
    neutrino_mask = ak.zeros_like(initial_pdg, dtype=bool)
    # Add every supported flavor to the selection.
    for pdg in FLAVOR_PDGS:
        # Combine this flavor with the existing event-level particle mask.
        neutrino_mask = neutrino_mask | (initial_pdg == pdg)
    # Count selected incoming neutrinos in every event.
    neutrinos_per_event = np.asarray(ak.sum(neutrino_mask, axis=1), dtype=int)
    # Require exactly one incoming atmospheric neutrino per interaction.
    if not np.all(neutrinos_per_event == 1):
        # Report the malformed event count rather than choosing an arbitrary neutrino.
        raise ValueError(f"Expected one atmospheric neutrino per event; {np.count_nonzero(neutrinos_per_event != 1)} events differ.")
    # Extract one incoming flavor per event.
    flavor = np.asarray(ak.firsts(initial_pdg[neutrino_mask]), dtype=int)
    # Extract one incoming total energy per event in MeV.
    energy = np.asarray(ak.firsts(arrays["generator_initial_particle_energy"][neutrino_mask]), dtype=float)
    # Extract aligned incoming Cartesian momentum components.
    px = np.asarray(ak.firsts(arrays["generator_initial_particle_px"][neutrino_mask]), dtype=float)
    # Extract incoming y momentum.
    py = np.asarray(ak.firsts(arrays["generator_initial_particle_py"][neutrino_mask]), dtype=float)
    # Extract incoming z momentum.
    pz = np.asarray(ak.firsts(arrays["generator_initial_particle_pz"][neutrino_mask]), dtype=float)
    # Calculate incoming momentum magnitude.
    momentum = np.sqrt(px * px + py * py + pz * pz)
    # Require nonzero momentum for all generated neutrinos.
    if np.any(momentum <= 0.0):
        # Reject undefined directions explicitly.
        raise ValueError("At least one incoming neutrino has zero momentum.")
    # Calculate detector-coordinate cos(theta_z).
    cos_zenith = pz / momentum
    # Calculate azimuth in degrees over the conventional [-180, 180] interval.
    azimuth = np.degrees(np.arctan2(py, px))
    # Read generator final-state particle identifiers for interaction-outcome checks.
    final_pdg = arrays["generator_final_particle_pdg_code"]
    # Count stable generator final-state particles per event.
    final_multiplicity = np.asarray(ak.num(final_pdg, axis=1), dtype=int)
    # Prepare a Boolean charged-current-like classification.
    cc_like = np.zeros(event_count, dtype=bool)
    # Check for the expected charged lepton for each incoming flavor.
    for pdg in FLAVOR_PDGS:
        # Select events with this incoming flavor.
        flavor_events = flavor == pdg
        # Check each event for at least one expected charged lepton.
        expected_present = np.asarray(ak.any(final_pdg == EXPECTED_CHARGED_LEPTON[pdg], axis=1), dtype=bool)
        # Mark matching events as charged-current-like.
        cc_like[flavor_events] = expected_present[flavor_events]
    # Count every incoming flavor.
    flavor_counts = {pdg: int(np.count_nonzero(flavor == pdg)) for pdg in FLAVOR_PDGS}
    # Calculate per-flavor median energies.
    flavor_median_energy = {pdg: float(np.median(energy[flavor == pdg])) for pdg in FLAVOR_PDGS}
    # Calculate per-flavor mean energies to expose high-energy-tail sensitivity.
    flavor_mean_energy = {pdg: float(np.mean(energy[flavor == pdg])) for pdg in FLAVOR_PDGS}
    # Calculate per-flavor median detector-coordinate cosines.
    flavor_median_cosine = {pdg: float(np.median(cos_zenith[flavor == pdg])) for pdg in FLAVOR_PDGS}
    # Calculate per-flavor mean detector-coordinate cosines as a complementary symmetry check.
    flavor_mean_cosine = {pdg: float(np.mean(cos_zenith[flavor == pdg])) for pdg in FLAVOR_PDGS}
    # Calculate per-flavor charged-current-like fractions.
    flavor_cc_fraction = {pdg: float(np.mean(cc_like[flavor == pdg])) for pdg in FLAVOR_PDGS}
    # Build common logarithmic energy bins spanning the complete sample.
    energy_bins = np.geomspace(np.min(energy) * 0.999, np.max(energy) * 1.001, 28)
    # Open the plot-collection PDF.
    with PdfPages(plot_pdf_path) as plot_pdf:
        # Create the flavor-composition overview page.
        figure, axes = plt.subplots(1, 2, figsize=(11, 4.8))
        # Collect counts in the fixed flavor order.
        ordered_counts = [flavor_counts[pdg] for pdg in FLAVOR_PDGS]
        # Draw flavor counts.
        flavor_bars = axes[0].bar([FLAVOR_LABELS[pdg] for pdg in FLAVOR_PDGS], ordered_counts,
                                  color=[FLAVOR_COLORS[pdg] for pdg in FLAVOR_PDGS])
        # Label every flavor bar with count and sample fraction.
        axes[0].bar_label(flavor_bars,
                          labels=[f"{count:,}\n({count / event_count:.1%})" for count in ordered_counts], padding=3, fontsize=9)
        # Label the flavor panel precisely as generated interactions.
        axes[0].set(title="Incoming flavor composition", ylabel="Generated interactions")
        # Leave headroom so the tallest count label does not compete with the panel title.
        axes[0].set_ylim(0.0, max(ordered_counts) * 1.16)
        # Count neutrino and antineutrino interactions.
        sign_counts = [int(np.count_nonzero(flavor > 0)), int(np.count_nonzero(flavor < 0))]
        # Draw the particle-sign comparison.
        sign_bars = axes[1].bar(["Neutrinos", "Antineutrinos"], sign_counts, color=["#4daf4a", "#984ea3"])
        # Label each sign category with count and fraction.
        axes[1].bar_label(sign_bars,
                          labels=[f"{count:,}\n({count / event_count:.1%})" for count in sign_counts], padding=3, fontsize=9)
        # Label the sign panel.
        axes[1].set(title="Neutrino versus antineutrino", ylabel="Generated interactions")
        # Leave headroom for the neutrino count and fraction label.
        axes[1].set_ylim(0.0, max(sign_counts) * 1.16)
        # Add the exact unweighted interaction-sample ratio.
        annotate(axes[1], [f"nu/anti-nu ratio: {sign_counts[0] / sign_counts[1]:.2f}",
                           "Counts include flux and cross-section sampling"])
        # Add a page title.
        figure.suptitle(f"Atmospheric-neutrino truth overview ({event_count:,} interactions)")
        # Save the overview page and PNG.
        save_plot(plot_pdf, figure, png_directory / "01_neutrino_flavor_composition.png")

        # Create the energy-distribution page.
        figure, axes = plt.subplots(1, 2, figsize=(11, 4.8))
        # Draw one incoming-energy spectrum per flavor.
        for pdg in FLAVOR_PDGS:
            # Select this flavor's energies.
            selected_energy = energy[flavor == pdg]
            # Draw the unweighted interaction spectrum.
            axes[0].hist(selected_energy, bins=energy_bins, histtype="step", linewidth=1.8,
                         color=FLAVOR_COLORS[pdg],
                         label=f"{FLAVOR_LABELS[pdg]}: N={len(selected_energy):,}, med={np.median(selected_energy):.0f}, mean={np.mean(selected_energy):.0f} MeV")
        # Use logarithmic energy for the broad atmospheric range.
        axes[0].set_xscale("log")
        # Label the spectrum as an interaction distribution.
        axes[0].set(title="Incoming energy by flavor", xlabel=r"Incoming $E_\nu$ [MeV]", ylabel="Generated interactions")
        # Display detailed flavor statistics.
        axes[0].legend(frameon=False, fontsize=8.5)
        # Count each flavor in common energy bins.
        binned_flavor_counts = np.array([np.histogram(energy[flavor == pdg], bins=energy_bins)[0] for pdg in FLAVOR_PDGS])
        # Calculate total interactions in every energy bin.
        binned_totals = np.sum(binned_flavor_counts, axis=0)
        # Calculate flavor fractions only in populated bins.
        binned_fractions = np.divide(binned_flavor_counts, binned_totals, out=np.zeros_like(binned_flavor_counts, dtype=float),
                                     where=binned_totals > 0)
        # Draw stacked flavor fractions using bin-left positions and widths.
        bottom = np.zeros(len(energy_bins) - 1)
        # Stack flavors in the fixed legend order.
        for row, pdg in enumerate(FLAVOR_PDGS):
            # Draw this flavor's fractional contribution.
            axes[1].bar(energy_bins[:-1], binned_fractions[row], width=np.diff(energy_bins), bottom=bottom,
                        align="edge", color=FLAVOR_COLORS[pdg], alpha=0.85, label=FLAVOR_LABELS[pdg])
            # Advance the stack baseline.
            bottom += binned_fractions[row]
        # Use logarithmic energy bins on the displayed x axis.
        axes[1].set_xscale("log")
        # Bound fractions to their physical interval.
        axes[1].set_ylim(0.0, 1.0)
        # Label the energy-dependent composition panel.
        axes[1].set(title="Flavor fraction versus energy", xlabel=r"Incoming $E_\nu$ [MeV]", ylabel="Fraction of interactions")
        # Display the flavor key.
        axes[1].legend(frameon=False, fontsize=8.5, ncol=2)
        # Add overall energy statistics.
        annotate(axes[1], [f"Overall median: {np.median(energy):.0f} MeV",
                           f"Overall mean: {np.mean(energy):.0f} MeV",
                           f"Central 90%: {np.percentile(energy, 5):.0f}-{np.percentile(energy, 95):.0f} MeV"])
        # Add a page title.
        figure.suptitle("Generated atmospheric-neutrino energy")
        # Save the energy page and PNG.
        save_plot(plot_pdf, figure, png_directory / "02_neutrino_energy.png")

        # Create the incoming-direction page.
        figure, axes = plt.subplots(1, 2, figsize=(11, 4.8))
        # Draw cos(theta_z) for each flavor.
        for pdg in FLAVOR_PDGS:
            # Select this flavor's direction cosines.
            selected_cosine = cos_zenith[flavor == pdg]
            # Draw a common-range histogram.
            axes[0].hist(selected_cosine, bins=24, range=(-1.0, 1.0), histtype="step", linewidth=1.8,
                         color=FLAVOR_COLORS[pdg],
                         label=f"{FLAVOR_LABELS[pdg]}: N={len(selected_cosine):,}, med={np.median(selected_cosine):.2f}, mean={np.mean(selected_cosine):.2f}")
        # Label the detector-coordinate zenith proxy.
        axes[0].set(title="Incoming detector-coordinate direction", xlabel=r"$\cos\theta_z=p_z/|p|$", ylabel="Interactions")
        # Display flavor medians.
        axes[0].legend(frameon=False, fontsize=8.5)
        # Draw azimuth for each flavor.
        for pdg in FLAVOR_PDGS:
            # Select this flavor's azimuths.
            selected_azimuth = azimuth[flavor == pdg]
            # Draw the full circular range.
            axes[1].hist(selected_azimuth, bins=24, range=(-180.0, 180.0), histtype="step", linewidth=1.8,
                         color=FLAVOR_COLORS[pdg], label=f"{FLAVOR_LABELS[pdg]}: N={len(selected_azimuth):,}")
        # Label the azimuth panel.
        axes[1].set(title="Incoming azimuth", xlabel=r"$\phi=\mathrm{atan2}(p_y,p_x)$ [degrees]", ylabel="Interactions")
        # Display flavor counts.
        axes[1].legend(frameon=False, fontsize=8.5)
        # Explain the expected azimuth behavior.
        annotate(axes[1], ["A flat azimuth distribution is expected", "Arithmetic mean omitted: azimuth is circular"])
        # Add a page title.
        figure.suptitle("Generated atmospheric-neutrino direction")
        # Save the direction page and PNG.
        save_plot(plot_pdf, figure, png_directory / "03_neutrino_direction.png")

        # Create the energy-direction correlation page.
        figure, axes = plt.subplots(1, 2, figsize=(11, 4.8))
        # Draw event density in incoming energy and detector-coordinate cosine.
        energy_angle_density = axes[0].hexbin(energy, cos_zenith, gridsize=45, xscale="log", bins="log", mincnt=1, cmap="viridis")
        # Add an explicit density colorbar.
        figure.colorbar(energy_angle_density, ax=axes[0], label="Interactions per hexbin")
        # Label the two-dimensional distribution.
        axes[0].set(title="Energy versus direction", xlabel=r"Incoming $E_\nu$ [MeV]", ylabel=r"$\cos\theta_z$")
        # Build common cosine bins for a profile view.
        cosine_bins = np.linspace(-1.0, 1.0, 17)
        # Calculate cosine-bin centers.
        cosine_centers = 0.5 * (cosine_bins[:-1] + cosine_bins[1:])
        # Digitize each event into a cosine bin.
        cosine_bin_index = np.digitize(cos_zenith, cosine_bins) - 1
        # Calculate median energy in every populated cosine bin.
        median_energy_by_cosine = np.array([
            np.median(energy[cosine_bin_index == index]) if np.any(cosine_bin_index == index) else np.nan
            for index in range(len(cosine_centers))
        ])
        # Calculate event counts in the same bins.
        direction_counts, _ = np.histogram(cos_zenith, bins=cosine_bins)
        # Draw the median-energy profile.
        axes[1].plot(cosine_centers, median_energy_by_cosine, marker="o", color="#542788", linewidth=1.6)
        # Use logarithmic energy to preserve visible relative changes.
        axes[1].set_yscale("log")
        # Label the profile view.
        axes[1].set(title="Median energy versus direction", xlabel=r"$\cos\theta_z$ bin center",
                    ylabel=r"Median incoming $E_\nu$ [MeV]")
        # Add bin-occupancy context.
        annotate(axes[1], [f"Direction bins: {len(cosine_centers)}",
                           f"Events/bin: {np.min(direction_counts)}-{np.max(direction_counts)}"])
        # Add a page title.
        figure.suptitle("Atmospheric-neutrino energy-direction structure")
        # Save the correlation page and PNG.
        save_plot(plot_pdf, figure, png_directory / "04_neutrino_energy_direction.png")

        # Create the generator-outcome page.
        figure, axes = plt.subplots(1, 2, figsize=(11, 4.8))
        # Collect charged-current-like fractions in flavor order.
        cc_fractions = [flavor_cc_fraction[pdg] for pdg in FLAVOR_PDGS]
        # Draw the charged-current-like fraction bars.
        cc_bars = axes[0].bar([FLAVOR_LABELS[pdg] for pdg in FLAVOR_PDGS], cc_fractions,
                              color=[FLAVOR_COLORS[pdg] for pdg in FLAVOR_PDGS])
        # Label each fraction and numerator/denominator.
        axes[0].bar_label(cc_bars,
                          labels=[f"{fraction:.1%}\n({int(np.sum(cc_like & (flavor == pdg)))}/{flavor_counts[pdg]})"
                                  for fraction, pdg in zip(cc_fractions, FLAVOR_PDGS)], padding=3, fontsize=8.5)
        # Bound the probability axis and label the inference.
        axes[0].set(title="Charged-current-like outcome", ylabel="Fraction with expected charged lepton", ylim=(0.0, 1.05))
        # Explain that this is inferred from final-state identities.
        annotate(axes[0], ["CC-like is inferred from the expected", "e-/e+ or mu-/mu+ in generator final state"], (0.98, 0.48))
        # Draw energy versus final-state multiplicity.
        multiplicity_density = axes[1].hexbin(energy, final_multiplicity, gridsize=(42, 22), xscale="log",
                                              bins="log", mincnt=1, cmap="magma")
        # Add a density colorbar.
        figure.colorbar(multiplicity_density, ax=axes[1], label="Interactions per hexbin")
        # Label the final-state complexity panel.
        axes[1].set(title="Final-state multiplicity versus energy", xlabel=r"Incoming $E_\nu$ [MeV]",
                    ylabel="Generator final-state particles")
        # Calculate correlation with log energy as a compact trend metric.
        multiplicity_correlation = float(np.corrcoef(np.log10(energy), final_multiplicity)[0, 1])
        # Add multiplicity statistics.
        annotate(axes[1], [f"Median multiplicity: {np.median(final_multiplicity):.0f}",
                           f"Mean: {np.mean(final_multiplicity):.2f}; central 90%: {np.percentile(final_multiplicity, 5):.0f}-{np.percentile(final_multiplicity, 95):.0f}",
                           f"corr(log10(E_nu), multiplicity): {multiplicity_correlation:.2f}"])
        # Add a page title.
        figure.suptitle("Generator interaction outcomes")
        # Save the outcome page and PNG.
        save_plot(plot_pdf, figure, png_directory / "05_neutrino_interaction_outcomes.png")

    # Count total charged-current-like outcomes.
    total_cc_like = int(np.count_nonzero(cc_like))
    # Calculate the unweighted particle-sign ratio.
    neutrino_to_antineutrino_ratio = float(np.count_nonzero(flavor > 0) / np.count_nonzero(flavor < 0))
    # Open the separate interpretation report PDF.
    with PdfPages(report_pdf_path) as report_pdf:
        # Add the definitions and sample-accounting page.
        add_report_page(report_pdf, "Atmospheric-neutrino truth report", [
            ("What this sample represents",
             "Each entry is a generated neutrino-argon interaction that was handed to Geant4. The incoming-neutrino "
             "distributions are therefore interaction distributions shaped by the atmospheric flux, the neutrino and "
             "antineutrino cross sections, the argon target, generator sampling, and any configured weights. They are "
             "not a direct plot of the unmodified atmospheric flux."),
            ("Truth extraction",
             f"Exactly one PDG 12, -12, 14, or -14 incoming neutrino was found in every one of the {event_count:,} "
             "events. Energy and direction come from generator_initial_particle_energy and the initial px, py, pz "
             "branches. Final-state multiplicity and charged-current-like classifications use the generator final-state "
             "PDG list, before Geant4 creates transport secondaries."),
            ("Flavor accounting",
             "The interaction counts are " + ", ".join(
                 f"{FLAVOR_NAMES[pdg]}={flavor_counts[pdg]:,} ({flavor_counts[pdg] / event_count:.1%})"
                 for pdg in FLAVOR_PDGS
             ) + f". The unweighted neutrino-to-antineutrino interaction ratio is {neutrino_to_antineutrino_ratio:.2f}. "
             "A neutrino excess is physically reasonable because the atmospheric flux and interaction cross sections "
             "both differ between neutrinos and antineutrinos."),
            ("Interpretation caution",
             "Do not compare these raw flavor bars directly with a published flux table unless the generator exposure, "
             "solid-angle integration, cross-section sampling, oscillations, and event weights are treated consistently. "
             "Their strongest immediate use is bookkeeping and regression validation of this exact production chain."),
        ], "Neutrino truth report 1 of 3")
        # Add the energy and direction interpretation page.
        add_report_page(report_pdf, "Energy and direction interpretation", [
            ("Incoming energy",
             f"The overall median incoming energy is {np.median(energy):.0f} MeV, the mean is {np.mean(energy):.0f} MeV, and the central 90% interval is "
             f"{np.percentile(energy, 5):.0f} to {np.percentile(energy, 95):.0f} MeV. Per-flavor medians are "
             + ", ".join(f"{FLAVOR_NAMES[pdg]}={flavor_median_energy[pdg]:.0f} MeV" for pdg in FLAVOR_PDGS)
             + "; per-flavor means are "
             + ", ".join(f"{FLAVOR_NAMES[pdg]}={flavor_mean_energy[pdg]:.0f} MeV" for pdg in FLAVOR_PDGS)
             + ". The mean is larger than the median when the high-energy tail is influential; the median is therefore "
             "the steadier typical-event metric, while the mean describes the sample's total energy budget. Differences "
             "among flavors can arise from flavor-dependent atmospheric fluxes and charged- "
             "and neutral-current interaction probabilities."),
            ("Flavor fraction versus energy",
             "The stacked fraction panel reveals whether flavor composition changes across energy without allowing the "
             "steep total spectrum to dominate the view. Smooth evolution is physically plausible; isolated jumps in "
             "the sparsely populated highest-energy bins should be interpreted as finite-sample fluctuations."),
            ("Detector-coordinate direction",
             "The cos(theta_z) plot uses the simulation z axis. It becomes a conventional atmospheric zenith plot only "
             "after confirming the flux-to-detector coordinate mapping and sign convention. Atmospheric fluxes can have "
             "real zenith dependence, and oscillations can strongly reshape flavor and zenith distributions, so exact "
             "flatness is not generally required. Per-flavor median/mean cos(theta_z) values are "
             + ", ".join(f"{FLAVOR_NAMES[pdg]}={flavor_median_cosine[pdg]:.2f}/{flavor_mean_cosine[pdg]:.2f}" for pdg in FLAVOR_PDGS)
             + "."),
            ("Azimuth and energy-angle structure",
             "Azimuth should be approximately uniform when the generation has no detector-orientation weighting. The "
             "energy-angle density and median-energy profile expose directional energy biases that separate one- "
             "dimensional plots can hide. Any strong periodic azimuth structure would warrant checking the flux rotation "
             "and momentum-coordinate transformation."),
        ], "Neutrino truth report 2 of 3")
        # Add the interaction-outcome and validation page.
        add_report_page(report_pdf, "Interaction outcome assessment", [
            ("Charged-current-like classification",
             f"The expected charged lepton appears in {total_cc_like:,} of {event_count:,} events ({total_cc_like / event_count:.1%}). "
             "Per-flavor fractions are " + ", ".join(
                 f"{FLAVOR_NAMES[pdg]}={flavor_cc_fraction[pdg]:.1%}" for pdg in FLAVOR_PDGS
             ) + ". The remainder are predominantly neutral-current-like under this PDG-based definition. This is a "
             "truth-topology inference, not a direct readout of GENIE's interaction-mode code."),
            ("Final-state complexity",
             f"The median generator final-state multiplicity is {np.median(final_multiplicity):.0f}, the mean is "
             f"{np.mean(final_multiplicity):.2f}, and the central 90% spans {np.percentile(final_multiplicity, 5):.0f} to "
             f"{np.percentile(final_multiplicity, 95):.0f} particles. Its correlation with log10 incoming "
             f"energy is {multiplicity_correlation:.2f}. A positive trend is physically expected because higher-energy "
             "interactions have more phase space for resonance production, deep-inelastic scattering, and larger "
             "hadronic systems."),
            ("Overall assessment",
             "The flavor accounting, broad energy spectra, populated all-sky directions, approximately uniform azimuth, "
             "charged-lepton sign logic, and increasing final-state complexity provide complementary generator sanity "
             "checks. None alone establishes an absolute atmospheric event rate, but together they can reveal unit "
             "errors, missing flavors, direction-convention mistakes, or broken generator-to-Geant4 truth handoff."),
            ("Recommended quantitative validation",
             "Preserve event weights and compare the incoming energy-flavor-zenith distribution against the exact Honda "
             "table and generation configuration. Then compare charged-current and neutral-current fractions and final- "
             "state observables under GENIE tune and cross-section systematic variations. Apply oscillation probabilities "
             "before comparing with an underground detector's expected atmospheric-neutrino data."),
        ], "Neutrino truth report 3 of 3")
    # Write a concise machine-readable text summary beside the figures.
    summary_lines = [
        "Atmospheric-neutrino generator-truth summary",
        f"Input: {input_path}",
        f"Events: {event_count}",
        f"Energy median MeV: {np.median(energy):.6f}",
        f"Energy mean MeV: {np.mean(energy):.6f}",
        f"Energy central 90% MeV: {np.percentile(energy, 5):.6f}, {np.percentile(energy, 95):.6f}",
        f"Neutrino/antineutrino interaction ratio: {neutrino_to_antineutrino_ratio:.6f}",
        f"CC-like events: {total_cc_like} ({total_cc_like / event_count:.6f})",
        f"Final-state multiplicity median: {np.median(final_multiplicity):.6f}",
        f"Final-state multiplicity mean: {np.mean(final_multiplicity):.6f}",
        f"Correlation log10(E_nu) vs final multiplicity: {multiplicity_correlation:.6f}",
    ]
    # Add one summary line per flavor.
    for pdg in FLAVOR_PDGS:
        # Record this flavor's count, energy, direction, and CC-like fraction.
        summary_lines.append(
            f"{FLAVOR_NAMES[pdg]}: count={flavor_counts[pdg]}, median_energy_MeV={flavor_median_energy[pdg]:.6f}, "
            f"mean_energy_MeV={flavor_mean_energy[pdg]:.6f}, median_cos_theta_z={flavor_median_cosine[pdg]:.6f}, "
            f"mean_cos_theta_z={flavor_mean_cosine[pdg]:.6f}, cc_like_fraction={flavor_cc_fraction[pdg]:.6f}"
        )
    # Write the text summary with a trailing newline.
    (png_directory / "atmospheric_neutrino_truth_summary.txt").write_text("\n".join(summary_lines) + "\n")
    # Report the processed sample size.
    print(f"Read {event_count:,} atmospheric-neutrino interactions from {input_path}")
    # Report where the plot collection was written.
    print(f"Saved plot PDF to {plot_pdf_path}")
    # Report where the interpretation report was written.
    print(f"Saved report PDF to {report_pdf_path}")
    # Report where standalone plots were written.
    print(f"Saved 5 standalone neutrino PNGs to {png_directory}")


# Execute the workflow only when this file is run directly.
if __name__ == "__main__":
    # Enter the command-line analysis.
    main()
